# Generated by Django 5.2.8 on 2025-11-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('carrera', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='reporte',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='informes.alumno'),
        ),
    ]
